# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Event', models.CharField(max_length=264, unique=True)),
                ('Date_Event', models.DateField()),
                ('Guest_Number', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
