# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Guest_Number',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
